
[Reach]
	#How far away the player can place and break blocks.
	#Range: 0 ~ 1000
	reachCreative = 300
	#Maximum reach in survival without upgrades
	#Consume Power Level upgrades to permanently increase this.
	#Range: 0 ~ 1000
	reachLevel0 = 100
	#Range: 0 ~ 1000
	reachLevel1 = 100
	#Range: 0 ~ 1000
	reachLevel2 = 100
	#Range: 0 ~ 1000
	reachLevel3 = 100

[MaxBlocksPlacedAtOnce]
	#How many blocks can be placed in one click.
	#Range: 0 ~ 100000
	maxBlocksPlacedAtOnceCreative = 10000
	#In survival without upgrades
	#Consume Power Level upgrades to permanently increase this.
	#Set to 0 to disable Effortless Building until the player has increased their Building Power Level.
	#Range: 0 ~ 100000
	maxBlocksPlacedAtOnceLevel0 = 2048
	#Range: 0 ~ 100000
	maxBlocksPlacedAtOnceLevel1 = 2048
	#Range: 0 ~ 100000
	maxBlocksPlacedAtOnceLevel2 = 2048
	#Range: 0 ~ 100000
	maxBlocksPlacedAtOnceLevel3 = 2048

[MaxBlocksPerAxis]
	#How many blocks can be placed at once per axis when using build modes (e.g. walls).
	#Also affects the array modifier.
	#Range: 0 ~ 1000
	maxBlocksPerAxisCreative = 1000
	#In survival without upgrades
	#Consume Power Level upgrades to permanently increase this.
	#Range: 0 ~ 1000
	maxBlocksPerAxisLevel0 = 100
	#Range: 0 ~ 1000
	maxBlocksPerAxisLevel1 = 100
	#Range: 0 ~ 1000
	maxBlocksPerAxisLevel2 = 100
	#Range: 0 ~ 1000
	maxBlocksPerAxisLevel3 = 100

[MaxMirrorRadius]
	#The maximum (radial) mirror radius.
	#Range: 0 ~ 1000
	maxMirrorRadiusCreative = 200
	#Maximum reach in survival without upgrades
	#Consume Power Level upgrades upgrades to permanently increase this.
	#Range: 0 ~ 1000
	maxMirrorRadiusLevel0 = 100
	#Range: 0 ~ 1000
	maxMirrorRadiusLevel1 = 100
	#Range: 0 ~ 1000
	maxMirrorRadiusLevel2 = 100
	#Range: 0 ~ 1000
	maxMirrorRadiusLevel3 = 100

